# Generated by Django 5.2.17 on 2026-10-03 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_email', models.CharField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Restore', 'Restore'), ('Status Change', 'Status Change'), ('Approve', 'Approve'), ('Reject', 'Reject'), ('Login', 'Login'), ('Logout', 'Logout'), ('Login Failed', 'Login Failed'), ('Password Change', 'Password Change'), ('Export', 'Export'), ('Download', 'Download'), ('Config Change', 'Config Change'), ('Permission Change', 'Permission Change'), ('Support Access', 'Support Access'), ('Import', 'Import')], max_length=30)),
                ('entity_type', models.CharField(blank=True, max_length=60)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('entity_label', models.CharField(blank=True, max_length=250)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('request_id', models.CharField(blank=True, max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'occurred_at'], name='core_auditl_organiz_39f898_idx'), models.Index(fields=['organization', 'entity_type', 'entity_id'], name='core_auditl_organiz_d64045_idx')],
            },
        ),
    ]
